# Generated by Django 4.2 on 2023-05-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='iframe',
        ),
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
    ]
