# Generated by Django 4.2 on 2023-05-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideofile', '0003_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploadvideofile.uploader'),
        ),
    ]
