# Generated by Django 4.2 on 2023-05-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideofile', '0004_media_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploader',
            old_name='password',
            new_name='reddit_password',
        ),
        migrations.RenameField(
            model_name='uploader',
            old_name='account',
            new_name='reddit_user',
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploader',
            name='fb_access_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
