# Generated by Django 4.2 on 2023-05-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
    ('uploadvideofile', '0001_initial'),
    # Other valid dependencies


    ]

    operations = [
    ]
