# Generated by Django 4.2 on 2023-05-23 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadvideofile', '0005_rename_password_uploader_reddit_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
