# Generated by Django 4.2 on 2023-05-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideofile', '0005_rename_password_uploader_reddit_password_and_more'),
        ('uploadvideofile', '0006_merge_20230517_1812'),
    ]

    operations = [
    ]
