# Generated by Django 4.2 on 2023-05-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideofile', '0006_alter_media_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='reddit_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='reddit_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
