# Generated by Django 4.2 on 2023-05-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideofile', '0007_alter_uploader_name_alter_uploader_reddit_password_and_more'),
        ('uploadvideofile', '0007_merge_20230517_1830'),
    ]

    operations = [
    ]
