# Generated by Django 4.2 on 2023-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideofile', '0007_merge_20230517_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='video_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='fb_access_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='reddit_password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='reddit_user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
