# Generated by Django 4.2.1 on 2023-05-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideofile', '0008_alter_media_description_alter_media_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploader',
            name='reddit_password',
        ),
        migrations.RemoveField(
            model_name='uploader',
            name='reddit_user',
        ),
        migrations.AddField(
            model_name='uploader',
            name='subreddit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
