# Generated by Django 4.2.1 on 2023-05-30 05:25

from django.db import migrations, models
import uploadvideofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideofile', '0011_rename_reddit_password_uploader_subreddit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(upload_to='videosdatabase', validators=[uploadvideofile.models.validate_file_extension]),
        ),
    ]
