# Generated by Django 4.2.1 on 2023-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=250)),
                ('video_description', models.CharField(max_length=250)),
                ('file_path', models.CharField(max_length=250)),
                ('access_key', models.CharField(max_length=600)),
            ],
        ),
    ]
